Repository DioneMartins/biblioteca-cp2, pull requests merged in 2022-03, with the labels that each got.

#13 Feature/desktop css
  src/components/navbar/Navbar.module.css
Labels: good first issue, refactor

#12 Feature/log books
  .eslintrc
  src/api/api.js
  src/api/login.js
  src/app/App.jsx
  src/app/Vars.css
  src/components/bookCards/BookCard.jsx
  src/components/bookCards/bookCardItem/BookCardItem.jsx
  src/components/bookCards/bookCardItem/BookCardItem.module.css
  src/components/logged/Logged.jsx
  src/components/logged/Logged.module.css
  src/components/logged/textToUpdate/TextToUpdate.jsx
  src/components/logged/textToUpdate/TextToUpdate.module.css
  src/components/loginComponent/LoginComponent.jsx
  src/pages/index.jsx
  src/pages/newBookPage/NewBookPage.jsx
  src/pages/newBookPage/NewBookPage.module.css
  src/pages/search/Search.jsx
  src/router/Router.jsx
Labels: enhancement

#15 Removed finished placeholders
  src/pages/home/Home.jsx
  src/pages/list/List.jsx
Labels: enhancement, good first issue

#14 Feature/init cards
  src/api/api.js
  src/components/bookCards/bookCardItem/BookCardItem.jsx
  src/components/homeCards/HomeCards.jsx
  src/components/homeCards/HomeCards.module.css
  src/components/homeCards/homeCarditem/HomeCardItem.jsx
  src/components/homeCards/homeCarditem/HomeCardItem.module.css
  src/components/index.jsx
  src/pages/home/Home.jsx
Labels: enhancement

#16 Feature/footer
  src/components/footer/Footer.jsx
  src/components/footer/Footer.module.css
  src/components/index.jsx
  src/components/navbar/Navbar.module.css
  src/pages/home/Home.jsx
  src/pages/list/List.jsx
  src/pages/login/Login.jsx
  src/pages/search/Search.jsx
Labels: enhancement

#18 Feature/pagination
  src/api/api.js
  src/assets/Antu_arrow-up.svg
  src/assets/Font_Awesome_5_solid_random.svg
  src/components/bookCards/BookCard.jsx
  src/components/index.jsx
  src/components/paginationFooter/PaginationFooter.jsx
  src/components/paginationFooter/PaginationFooter.module.css
  src/components/paginationHeader/PaginationHeader.jsx
  src/components/paginationHeader/PaginationHeader.module.css
  src/pages/list/List.jsx
Labels: enhancement
